<a href="https://colab.research.google.com/github/AlekyaMadiReddy/Alekya_INFO5731_Fall2023/blob/main/MadiReddy_exercise_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## The third In-class-exercise (due on 11:59 PM 10/08/2023, 40 points in total)

The purpose of this exercise is to understand text representation.

Question 1 (10 points): Describe an interesting text classification or text mining task and explain what kind of features might be useful for you to build the machine learning model. List your features and explain why these features might be helpful. You need to list at least five different types of features.

In [1]:
# Your answer here (no code for this question, write down your answer as detail as possible for the above questions):

'''
Please write you answer here:
The categorization of articles of Coding research into categories like "Python," "C++," "Dbms," "Java," and "Pycharm" might be an intriguing text classification challenge in coding. Researchers might easily find suitable publications for their particular study interests with the help of this assignment.

The following five features may be used to create a machine learning model for this task:

Features of the Bag of Words (BoW): BoW features show how frequently each word appears in the text. These characteristics can aid in identifying the most prevalent words connected to each study category.
Term frequency-inverse document frequency, or TF-IDF Features: When comparing a word's relevance within a text to its importance throughout the entire corpus, TF-IDF is used. These qualities might draw attention to terms that are especially pertinent to a given field of study.

Features of N-grams: N-grams are groups of neighboring words or letters. Important textual phrases or patterns that may be indicative of the study category can be extracted using n-grams.

Word Embeddings: Word embeddings, like GloVe or Word2Vec, may turn words into detailed vector representations. The context of terms used in the text may be understood using these embeddings, which record the semantic links between words.

Topic Modeling Features: Topic modeling techniques like Latent Dirichlet Allocation (LDA) can identify the underlying topics in a document. These features can help categorize research articles based on the topics they cover


'''

'\nPlease write you answer here:\nThe categorization of articles of Coding\xa0research into categories like "Python," "C++," "Dbms," "Java," and "Pycharm" might be an intriguing text classification challenge in coding. Researchers might easily find suitable publications for their particular study interests with the help of this assignment.\n\nThe following five features may be used to create a machine learning model for this task:\n\nFeatures of the Bag of Words (BoW): BoW features show how frequently each word appears in the text. These characteristics can aid in identifying the most prevalent words connected to each study category.\nTerm frequency-inverse document frequency, or TF-IDF Features: When comparing a word\'s relevance within a text to its importance throughout the entire corpus, TF-IDF is used. These qualities might draw attention to terms that are especially pertinent to a given field of study.\n\nFeatures of N-grams: N-grams are groups of neighboring words or letters. Im

Question 2 (10 points): Write python code to extract these features you discussed above. You can collect a few sample text data for the feature extraction.

In [2]:
# You code here (Please add comments in the code):
import nltk
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation

# Sample coding research articles
documents = [
    "Blockchain Technology Demystified: Building Your First Blockchain Application",
    "Getting Started with React: Building User Interfaces the Modern Way",
    "Coding for IoT: Building Smart Devices with Arduino and Raspberry Pi",
    "Introduction to Functional Programming in Haskell: A Paradigm Shift",
]

# Tokenize and preprocess the text
nltk.download('punkt')
tokenized_documents = [nltk.word_tokenize(doc.lower()) for doc in documents]

# Bag of Words (BoW) features
vectorizer_bow = CountVectorizer()
bow_features = vectorizer_bow.fit_transform([" ".join(doc) for doc in tokenized_documents])

# TF-IDF features
vectorizer_tfidf = TfidfVectorizer()
tfidf_features = vectorizer_tfidf.fit_transform([" ".join(doc) for doc in tokenized_documents])

# N-grams features (bi-grams and tri-grams)
vectorizer_ngrams = CountVectorizer(ngram_range=(2, 3))
ngrams_features = vectorizer_ngrams.fit_transform([" ".join(doc) for doc in tokenized_documents])

# Topic modeling features using LDA
lda = LatentDirichletAllocation(n_components=2)
lda_features = lda.fit_transform(bow_features)

# Word embeddings (using pre-trained Word2Vec or GloVe embeddings)
# You would typically load pre-trained embeddings and transform the text into vectors.

# Display the extracted features
print("BoW Features:")
print(bow_features.toarray())

print("\nTF-IDF Features:")
print(tfidf_features.toarray())

print("\nN-grams Features:")
print(ngrams_features.toarray())

print("\nTopic Modeling Features (LDA):")
print(lda_features)




BoW Features:
[[0 1 0 2 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1]
 [0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 1 0 0 0 0 1 0 0 1 0 1 0 1 1 1 0]
 [1 0 1 0 1 1 0 1 0 1 0 0 0 0 0 0 1 0 0 1 0 1 0 0 1 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 1 0 0 1 0 1 0 0 1 0 0 0 0 1 0 0 0 0]]

TF-IDF Features:
[[0.         0.32603555 0.         0.6520711  0.20810427 0.
  0.32603555 0.         0.32603555 0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.         0.         0.         0.
  0.         0.         0.32603555 0.         0.         0.
  0.         0.         0.32603555]
 [0.         0.         0.         0.         0.21242036 0.
  0.         0.         0.         0.         0.         0.33279753
  0.         0.         0.33279753 0.         0.         0.33279753
  0.         0.         0.         0.         0.33279753 0.
  0.         0.33279753 0.         0.33279753 0.         0.33279753
  0.33279753 0.2623814  0.     

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


Question 3 (10 points): Use any of the feature selection methods mentioned in this paper "Deng, X., Li, Y., Weng, J., & Zhang, J. (2019). Feature selection for text classification: A review. Multimedia Tools & Applications, 78(3)."

Select the most important features you extracted above, rank the features based on their importance in the descending order.

In [3]:
from sklearn.feature_selection import SelectKBest, chi2

# Define the target labels (research categories)
labels = ["Python", "Supplychain", "Java", "Dbms"]

# Assuming you have a target label for each document, e.g., [0, 1, 2, 3]

# Feature selection using chi-squared statistic
k_best = SelectKBest(score_func=chi2, k='all')
selected_features = k_best.fit_transform(bow_features, labels)

# Get the indices of selected features in descending order of importance
sorted_feature_indices = (-k_best.scores_).argsort()

# List the features in descending order of importance
sorted_features = [vectorizer_bow.get_feature_names_out()[i] for i in sorted_feature_indices]

print("Top Features in Descending Order of Importance:")
print(sorted_features)

Top Features in Descending Order of Importance:
['blockchain', 'and', 'way', 'user', 'to', 'the', 'technology', 'started', 'smart', 'shift', 'react', 'raspberry', 'programming', 'pi', 'paradigm', 'modern', 'iot', 'introduction', 'interfaces', 'in', 'haskell', 'getting', 'functional', 'for', 'first', 'devices', 'demystified', 'coding', 'arduino', 'application', 'your', 'with', 'building']


Question 4 (10 points): Write python code to rank the text based on text similarity. Based on the text data you used for question 2, design a query to match the most relevant docments. Please use the BERT model to represent both your query and the text data, then calculate the cosine similarity between the query and each text in your data. Rank the similary with descending order.

In [4]:
pip install transformers


In [5]:
pip install torch torchvision torchaudio


In [7]:
import numpy as np
import torch
from sklearn.metrics.pairwise import cosine_similarity
from transformers import AutoTokenizer, AutoModel


# Your query
query = "Introduction to Functional Programming in Haskell: A Paradigm Shift"

# Load pre-trained BERT model and tokenizer
model_name = "bert-base-uncased"  # You can choose other BERT variants as well
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModel.from_pretrained(model_name)

# Encode the query and documents
query_encoding = tokenizer(query, return_tensors="pt", padding=True, truncation=True)
document_encodings = tokenizer(documents, return_tensors="pt", padding=True, truncation=True)

# Get BERT embeddings for the query and documents
with torch.no_grad():
    query_embedding = model(**query_encoding).last_hidden_state.mean(dim=1)
    document_embeddings = model(**document_encodings).last_hidden_state.mean(dim=1)

# Calculate cosine similarity between the query and documents
similarities = cosine_similarity(query_embedding, document_embeddings).flatten()

# Rank documents by similarity in descending order
ranked_documents = [(document, similarity) for document, similarity in zip(documents, similarities)]
ranked_documents.sort(key=lambda x: x[1], reverse=True)

# Print ranked documents
for i, (document, similarity) in enumerate(ranked_documents, start=1):
    print(f"Rank {i}: Similarity = {similarity:.4f}")
    print(document)
    print()


Rank 1: Similarity = 0.9539
Introduction to Functional Programming in Haskell: A Paradigm Shift

Rank 2: Similarity = 0.6811
Getting Started with React: Building User Interfaces the Modern Way

Rank 3: Similarity = 0.6350
Coding for IoT: Building Smart Devices with Arduino and Raspberry Pi

Rank 4: Similarity = 0.6158
Blockchain Technology Demystified: Building Your First Blockchain Application

